name: rake
description: A basic implementation of RAKE (Rapid Automatic Keyword Extraction.
version: 1.0.1
homepage: https://github.com/mathisgerdes/dart-rake
author: Mathis Gerdes <mathisgerdes@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
